export {MyMetadata} from "./MyMetadata"
export {MyMenu} from "./MyMenu"
export {MyContact} from "./MyContact"
export {MyNamespace} from "./MyNamespace"
export {MyHeader} from "./MyHeader"
export {MyHeroPage} from "./MyHeroPage"